"use client";

import { useState, useEffect, useCallback } from "react";
import { useSession } from "next-auth/react";
import { Brain, RefreshCw, Crown, Calendar } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { MealPlanDisplay } from "@/components/meal-plan/meal-plan-display";
import { PaywallModal } from "@/components/subscription/paywall-modal";
import { toast } from "@/components/ui/use-toast";
import { formatDate } from "@/utils/formatters";
import type { MealPlanRecord } from "@/types";

export default function MealPlanPage() {
  const { data: session } = useSession();
  const [mealPlan, setMealPlan] = useState<MealPlanRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [showPaywall, setShowPaywall] = useState(false);

  const isPremium = session?.user?.subscriptionStatus === "PREMIUM";

  const fetchMealPlan = useCallback(async () => {
    try {
      const res = await fetch("/api/meal-plan");
      if (res.ok) {
        const data = await res.json() as { mealPlan: MealPlanRecord | null };
        setMealPlan(data.mealPlan);
      }
    } catch {
      // silent
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchMealPlan(); }, [fetchMealPlan]);

  const handleGenerate = async () => {
    if (!isPremium) {
      setShowPaywall(true);
      return;
    }

    setGenerating(true);
    try {
      const res = await fetch("/api/meal-plan", { method: "POST" });
      const data = await res.json() as { mealPlan?: MealPlanRecord; error?: string };

      if (!res.ok) {
        throw new Error(data.error ?? "Failed to generate meal plan");
      }

      setMealPlan(data.mealPlan ?? null);
      toast({ title: "Meal plan generated!", description: "Your 7-day plan is ready.", variant: "success" });
    } catch (err) {
      toast({
        title: "Generation failed",
        description: err instanceof Error ? err.message : "Please try again",
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-xl font-bold text-gray-900">AI Meal Plans</h2>
          <p className="text-sm text-gray-500 mt-0.5">
            Personalized 7-day meal plans generated by AI
          </p>
        </div>
        <div className="flex items-center gap-3">
          {!isPremium && (
            <Badge variant="amber" className="flex items-center gap-1">
              <Crown className="h-3 w-3" />
              Premium Feature
            </Badge>
          )}
          <Button
            variant="emerald"
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? (
              <>
                <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Brain className="h-4 w-4 mr-2" />
                {mealPlan ? "Regenerate Plan" : "Generate Weekly Plan"}
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Loading state */}
      {loading && (
        <Card>
          <CardContent className="py-16 text-center text-gray-400">
            Loading your meal plan...
          </CardContent>
        </Card>
      )}

      {/* No plan yet */}
      {!loading && !mealPlan && (
        <Card className="border-dashed">
          <CardContent className="py-16 text-center">
            <Brain className="h-12 w-12 text-gray-300 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-gray-700 mb-2">
              No meal plan yet
            </h3>
            <p className="text-gray-500 text-sm max-w-sm mx-auto mb-6">
              {isPremium
                ? "Click \"Generate Weekly Plan\" to create your personalized AI meal plan based on your goals and dietary preferences."
                : "Upgrade to Premium to unlock AI-powered weekly meal plans tailored to your goals."}
            </p>
            <Button variant="emerald" onClick={handleGenerate} disabled={generating}>
              <Brain className="h-4 w-4 mr-2" />
              {isPremium ? "Generate My Plan" : "Upgrade to Generate"}
            </Button>
          </CardContent>
        </Card>
      )}

      {/* Meal plan display */}
      {!loading && mealPlan && (
        <div className="space-y-4">
          <div className="flex items-center gap-2 text-sm text-gray-500">
            <Calendar className="h-4 w-4" />
            Week starting {formatDate(mealPlan.weekStartDate)}
            <span className="text-gray-300">•</span>
            Generated {formatDate(mealPlan.createdAt)}
          </div>
          <Card>
            <CardContent className="pt-6">
              <MealPlanDisplay plan={mealPlan.planJSON} />
            </CardContent>
          </Card>
        </div>
      )}

      {/* Paywall modal */}
      <PaywallModal open={showPaywall} onClose={() => setShowPaywall(false)} />
    </div>
  );
}
