import Link from "next/link";
import {
  Leaf,
  TrendingUp,
  Brain,
  BarChart3,
  ShoppingCart,
  Shield,
  Star,
  ArrowRight,
  Check,
  Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

const FEATURES = [
  {
    icon: BarChart3,
    title: "Smart Calorie Tracking",
    description:
      "Log your meals in seconds using our food database of 50+ common foods or manual entry. See remaining macros in real-time.",
    color: "bg-blue-100 text-blue-600",
  },
  {
    icon: Brain,
    title: "AI Meal Plan Generator",
    description:
      "Get a personalized 7-day meal plan generated by GPT-4, tailored to your goals, calorie targets, and dietary preferences.",
    color: "bg-purple-100 text-purple-600",
  },
  {
    icon: TrendingUp,
    title: "Progress-Driven Adjustments",
    description:
      "Weekly weight analysis automatically adjusts your calorie targets — plateau-busting and overshoot protection built in.",
    color: "bg-emerald-100 text-emerald-600",
  },
  {
    icon: ShoppingCart,
    title: "Grocery List Generation",
    description:
      "Every AI meal plan comes with a complete, organized grocery list so you can shop efficiently for the whole week.",
    color: "bg-amber-100 text-amber-600",
  },
];

const PRICING = [
  {
    name: "Free",
    price: "$0",
    period: "forever",
    features: [
      "Food & calorie logging",
      "Macro tracking",
      "Basic dashboard",
      "Weight logging",
    ],
    cta: "Get Started Free",
    href: "/register",
    highlight: false,
  },
  {
    name: "Premium",
    price: "$9.99",
    period: "/month",
    features: [
      "Everything in Free",
      "AI weekly meal plans",
      "Smart calorie adjustments",
      "Grocery list generation",
      "Advanced progress insights",
      "Priority support",
    ],
    cta: "Start Premium",
    href: "/register",
    highlight: true,
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 bg-white/95 backdrop-blur border-b border-gray-100">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 flex items-center justify-between h-16">
          <div className="flex items-center gap-2">
            <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-emerald-600">
              <Leaf className="h-4 w-4 text-white" />
            </div>
            <span className="text-lg font-bold text-gray-900">NutriGoal</span>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/login">
              <Button variant="ghost" size="sm">
                Sign in
              </Button>
            </Link>
            <Link href="/register">
              <Button variant="emerald" size="sm">
                Get Started Free
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative overflow-hidden bg-gradient-to-b from-emerald-50 to-white pt-20 pb-24">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center">
          <Badge variant="emerald" className="mb-6 px-4 py-1.5 text-xs font-semibold inline-flex">
            <Zap className="h-3 w-3 mr-1.5" />
            AI-Powered Nutrition Tracking
          </Badge>
          <h1 className="text-5xl sm:text-6xl font-extrabold text-gray-900 leading-tight tracking-tight">
            Reach Your Goals with{" "}
            <span className="text-emerald-600">Smarter Nutrition</span>
          </h1>
          <p className="mt-6 text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
            NutriGoal combines calorie tracking, macro management, and AI-generated meal
            plans to create a personalized nutrition system that adapts to your progress.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center mt-10">
            <Link href="/register">
              <Button variant="emerald" size="xl" className="w-full sm:w-auto">
                Start For Free
                <ArrowRight className="h-5 w-5 ml-2" />
              </Button>
            </Link>
            <Link href="/login">
              <Button variant="outline" size="xl" className="w-full sm:w-auto">
                Sign In
              </Button>
            </Link>
          </div>
          <p className="mt-4 text-sm text-gray-400">
            No credit card required · Free plan available forever
          </p>
        </div>

        {/* Hero visual */}
        <div className="mt-16 max-w-5xl mx-auto px-4 sm:px-6">
          <div className="bg-white rounded-2xl shadow-2xl border border-gray-100 overflow-hidden">
            <div className="bg-gray-50 px-4 py-3 flex items-center gap-2 border-b">
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-red-400" />
                <div className="w-3 h-3 rounded-full bg-amber-400" />
                <div className="w-3 h-3 rounded-full bg-emerald-400" />
              </div>
              <div className="flex-1 bg-white rounded-md px-3 py-1 text-xs text-gray-400 text-center border">
                app.nutrigoal.com/dashboard
              </div>
            </div>
            <div className="p-6 grid grid-cols-3 gap-4">
              <div className="col-span-2 space-y-4">
                <div className="bg-emerald-50 rounded-xl p-4">
                  <p className="text-xs font-medium text-emerald-700 mb-1">Daily Calories</p>
                  <p className="text-2xl font-bold text-gray-900">1,450 <span className="text-sm font-normal text-gray-500">/ 2,100 kcal</span></p>
                  <div className="mt-2 h-2.5 bg-gray-200 rounded-full overflow-hidden">
                    <div className="h-full w-[69%] bg-emerald-500 rounded-full" />
                  </div>
                </div>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { label: "Protein", val: "142g", pct: 89, color: "bg-blue-500" },
                    { label: "Carbs", val: "156g", pct: 65, color: "bg-amber-500" },
                    { label: "Fat", val: "48g", pct: 77, color: "bg-rose-500" },
                  ].map(({ label, val, pct, color }) => (
                    <div key={label} className="bg-gray-50 rounded-xl p-3">
                      <p className="text-xs text-gray-500">{label}</p>
                      <p className="font-bold text-gray-900">{val}</p>
                      <div className="mt-1.5 h-1.5 bg-gray-200 rounded-full overflow-hidden">
                        <div className={`h-full rounded-full ${color}`} style={{ width: `${pct}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="space-y-3">
                <div className="bg-purple-50 rounded-xl p-3">
                  <p className="text-xs font-medium text-purple-700">AI Meal Plan</p>
                  <p className="text-xs text-gray-600 mt-1">Week 3 active ✓</p>
                  <p className="text-xs text-gray-500 mt-1">Breakfast: Oat bowl</p>
                  <p className="text-xs text-gray-500">Lunch: Chicken salad</p>
                  <p className="text-xs text-gray-500">Dinner: Salmon rice</p>
                </div>
                <div className="bg-amber-50 rounded-xl p-3">
                  <p className="text-xs font-medium text-amber-700">This Week</p>
                  <p className="text-xs text-gray-600 mt-1">Weight: 78.2 kg</p>
                  <p className="text-xs text-emerald-600 font-medium">-0.8 kg ↓</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 max-w-6xl mx-auto px-4 sm:px-6">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-gray-900">
            Everything you need to succeed
          </h2>
          <p className="mt-4 text-gray-500 text-lg max-w-xl mx-auto">
            A complete nutrition system from tracking to AI meal planning
          </p>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-2 gap-6">
          {FEATURES.map(({ icon: Icon, title, description, color }) => (
            <div
              key={title}
              className="p-6 rounded-2xl border border-gray-100 bg-white hover:shadow-md transition-shadow"
            >
              <div className={`inline-flex items-center justify-center w-12 h-12 rounded-xl ${color} mb-4`}>
                <Icon className="h-6 w-6" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">{title}</h3>
              <p className="text-gray-500 text-sm leading-relaxed">{description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="py-24 bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900">How NutriGoal works</h2>
          </div>
          <div className="grid sm:grid-cols-3 gap-8">
            {[
              { step: "1", title: "Set Up Your Profile", desc: "Complete a quick onboarding with your body metrics, goal, and dietary preferences." },
              { step: "2", title: "Track & Plan", desc: "Log meals daily, let AI generate a weekly plan, and see your macros in real-time." },
              { step: "3", title: "Adapt & Progress", desc: "Weekly weight analysis automatically adjusts your calories so you keep making progress." },
            ].map(({ step, title, desc }) => (
              <div key={step} className="text-center">
                <div className="flex items-center justify-center w-14 h-14 rounded-2xl bg-emerald-600 text-white text-2xl font-bold mx-auto mb-4">
                  {step}
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">{title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-24 max-w-4xl mx-auto px-4 sm:px-6">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-gray-900">Simple, transparent pricing</h2>
          <p className="mt-4 text-gray-500">Start free, upgrade when you need AI power</p>
        </div>
        <div className="grid sm:grid-cols-2 gap-6">
          {PRICING.map(({ name, price, period, features, cta, href, highlight }) => (
            <div
              key={name}
              className={`rounded-2xl border p-8 ${
                highlight
                  ? "border-emerald-500 bg-emerald-600 text-white shadow-xl shadow-emerald-100"
                  : "border-gray-200 bg-white"
              }`}
            >
              {highlight && (
                <Badge className="mb-4 bg-white text-emerald-700 hover:bg-white">
                  Most Popular
                </Badge>
              )}
              <h3 className={`text-xl font-bold ${highlight ? "text-white" : "text-gray-900"}`}>
                {name}
              </h3>
              <div className="mt-2 mb-6">
                <span className={`text-4xl font-extrabold ${highlight ? "text-white" : "text-gray-900"}`}>
                  {price}
                </span>
                <span className={`text-sm ${highlight ? "text-emerald-200" : "text-gray-500"}`}>
                  {period}
                </span>
              </div>
              <ul className="space-y-3 mb-8">
                {features.map((f) => (
                  <li key={f} className="flex items-center gap-2.5 text-sm">
                    <Check
                      className={`h-4 w-4 shrink-0 ${
                        highlight ? "text-emerald-200" : "text-emerald-600"
                      }`}
                    />
                    <span className={highlight ? "text-emerald-50" : "text-gray-600"}>{f}</span>
                  </li>
                ))}
              </ul>
              <Link href={href} className="block">
                <Button
                  className="w-full"
                  variant={highlight ? "outline" : "emerald"}
                  size="lg"
                >
                  {cta}
                </Button>
              </Link>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 bg-emerald-600">
        <div className="max-w-2xl mx-auto px-4 sm:px-6 text-center">
          <h2 className="text-4xl font-bold text-white">
            Ready to transform your diet?
          </h2>
          <p className="mt-4 text-emerald-100 text-lg">
            Join thousands of users hitting their nutrition goals with NutriGoal.
          </p>
          <Link href="/register">
            <Button variant="outline" size="xl" className="mt-8 bg-white text-emerald-700 hover:bg-emerald-50 border-white">
              Start Free Today
              <ArrowRight className="h-5 w-5 ml-2" />
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 py-12 px-4 sm:px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="flex items-center justify-center w-7 h-7 rounded-md bg-emerald-600">
              <Leaf className="h-3.5 w-3.5 text-white" />
            </div>
            <span className="font-bold text-white">NutriGoal</span>
          </div>
          <p className="text-sm">© {new Date().getFullYear()} NutriGoal. All rights reserved.</p>
          <div className="flex gap-4 text-sm">
            <a href="#" className="hover:text-white transition-colors">Privacy</a>
            <a href="#" className="hover:text-white transition-colors">Terms</a>
            <a href="#" className="hover:text-white transition-colors">Support</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
